apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-midd-exporter
  namespace: prom-middleware
data:
  PG_DATABASE: xxxx
  PG_PORT: '5432'
  PG_DBNAME: postgres
  AWS_REGION: us-east-2
  AWS_RDS_INSTANCE_ID: instance-1
  SERVER_PORT: '9800'
  AWS_RDS_TYPE: DBInstanceIdentifier
  AWS_MONGO_INSTANCE_INFO: '{"DBInstanceIdentifier": ["produce", "produce2"],"DBClusterIdentifier": ["produce"]}'
  AWS_ELASTICACHE_INSTANCE_INFO: '{"CacheClusterId": ["production-001","production-002"]}'