apiVersion: v1
kind: Service
metadata:
    name: aws-midd-exporter
    namespace: prom-middleware
spec:
    selector:
        app: aws-midd-exporter
    ports:
    - name: aws-midd-exporter
      port: 9800
      targetPort: 9800