{
 "title": "MIDD-AWS-MONGODB-Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "instance", "label": "instance", "query": { "query": "query_result(mongo_up)" } }
  ]
 },
 "panels": [
  {
   "title": "版本",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongo_version_info{instance=\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "DocDB运行时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongo_uptime_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DocDB CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mongo_cpu_utilization{instance=\"$instance\"}",
     "legendFormat": "{{DocDB}}"
    }
   ]
  },
  {
   "title": "PostgreSQL 空闲内存",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mongo_freeable_memory{instance=\"$instance\"} ",
     "legendFormat": "{{DocDB}}"
    }
   ]
  },
  {
   "title": "网络传输吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "mongo_network_throughput{instance=\"$instance\"}",
     "legendFormat": "{{DocDB}}"
    }
   ]
  },
  {
   "title": "DocDB 连接数情况",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 6 },
   "targets": [
    {
     "expr": "mongo_current_connections{instance=\"$instance\"}",
     "legendFormat": "当前连接数"
    },
    {
     "expr": "mongo_available_connections{instance=\"$instance\"}",
     "legendFormat": "可用的连接数"
    }
   ]
  },
  {
   "title": "存储使用量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mongo_volume_bytesused{instance=\"$instance\"}",
     "legendFormat": "使用存储空间"
    }
   ]
  },
  {
   "title": "磁盘IOPS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "mongo_volume_readiops{instance=\"$instance\"}",
     "legendFormat": "磁盘读取iops"
    },
    {
     "expr": "mongo_volume_wriateiops{instance=\"$instance\"}",
     "legendFormat": "磁盘写入iops"
    }
   ]
  },
  {
   "title": "DocDB 读取写入延迟",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "mongo_read_latency{instance=\"$instance\"}",
     "legendFormat": "{{DocDB}}读取延迟"
    },
    {
     "expr": "mongo_write_latency{instance=\"$instance\"}",
     "legendFormat": "{{DocDB}}写入延迟"
    }
   ]
  },
  {
   "title": "DocDB 操作计数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "mongo_opcounters_insert{instance=\"$instance\"}",
     "legendFormat": "insert"
    },
    {
     "expr": "mongo_opcounters_query{instance=\"$instance\"}",
     "legendFormat": "query"
    },
    {
     "expr": "mongo_opcounters_update{instance=\"$instance\"}",
     "legendFormat": "update"
    },
    {
     "expr": "mongo_opcounters_delete{instance=\"$instance\"}",
     "legendFormat": "delete"
    },
    {
     "expr": "mongo_opcounters_getmore{instance=\"$instance\"}",
     "legendFormat": "getmore"
    },
    {
     "expr": "mongo_opcounters_command{instance=\"$instance\"}",
     "legendFormat": "command"
    }
   ]
  },
  {
   "title": "DocDB 文档操作统计",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "mongo_document_deleted{instance=\"$instance\"}",
     "legendFormat": "deleted"
    },
    {
     "expr": "mongo_document_inserted{instance=\"$instance\"}",
     "legendFormat": "inserted"
    },
    {
     "expr": "mongo_document_returned{instance=\"$instance\"}",
     "legendFormat": "returned"
    },
    {
     "expr": "mongo_document_updated{instance=\"$instance\"}",
     "legendFormat": "updated"
    }
   ]
  }
 ]
}