{
 "title": "MIDD-AWS-PGSQL-dashboard",
 "tags": [
  "AWS",
  "PGSQL"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(pg_uptime_seconds)"
    }
   },
   { "name": "pg_exporter", "label": "pg_exporter", "query": { "query": "query_result(pg_up)" } },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "mode",
    "label": "Lock table",
    "query": {
     "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"},mode)"
    }
   },
   { "name": "interval", "label": "interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "PostgreSQL 基础", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "版本",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{instance=\"$pg_exporter\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "PostgreSQL运行时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_uptime_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pg_cpu_utilization{instance=\"$instance\"}",
     "legendFormat": "CPU 使用率"
    }
   ]
  },
  {
   "title": "PostgreSQL 空闲内存",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_memory_utilization{instance=\"$instance\"} ",
     "legendFormat": "空闲内存"
    }
   ]
  },
  {
   "title": "PostgreSQL 使用的存储空间",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_storage_disk_space{instance=\"$instance\"}",
     "legendFormat": "使用存储空间"
    }
   ]
  },
  {
   "title": "PostgreSQL 网络传输吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "pg_network_throughput{instance=\"$instance\"}",
     "legendFormat": "网络吞吐量"
    }
   ]
  },
  {
   "title": "PostgreSQL 读取IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "pg_read_iops{instance=\"$instance\"}",
     "legendFormat": "读取IOPS"
    }
   ]
  },
  {
   "title": "PostgreSQL QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "pg_qps_all{instance=\"$instance\"}",
     "legendFormat": "ALL QPS"
    },
    {
     "expr": "pg_qps_read{instance=\"$instance\"}",
     "legendFormat": "Read QPS"
    },
    {
     "expr": "pg_qps_write{instance=\"$instance\"}",
     "legendFormat": "Write QPS"
    }
   ]
  },
  {
   "title": "PostgreSQL 连接数情况",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "pg_total_connections{instance=\"$instance\"}",
     "legendFormat": "数据库总连接数"
    },
    {
     "expr": "pg_active_connections{instance=\"$instance\"}",
     "legendFormat": "活跃的连接数"
    },
    {
     "expr": "pg_idle_connections{instance=\"$instance\"}",
     "legendFormat": "空闲连接数"
    }
   ]
  },
  {
   "title": "PostgreSQL User 对应的连接数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "pg_user_connection_count{instance=\"$instance\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Query信息",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "pg_query_calls{instance=\"$instance\"} - 0"
    },
    {
     "expr": "pg_query_total_exec_time{instance=\"$instance\"} - 0"
    },
    {
     "expr": "pg_query_min_exec_time{instance=\"$instance\"} - 0"
    },
    {
     "expr": "pg_query_max_exec_time{instance=\"$instance\"} - 0"
    },
    {
     "expr": "pg_query_mean_exec_time{instance=\"$instance\"} - 0"
    },
    {
     "expr": "pg_query_blk_read_time{instance=\"$instance\"} - 0"
    },
    {
     "expr": "pg_query_blk_write_time{instance=\"$instance\"} - 0"
    },
    {
     "expr": "pg_query_rows{instance=\"$instance\"} - 0"
    },
    {
     "expr": "pg_query_hit_percent{instance=\"$instance\"} - 0"
    }
   ]
  },
  {
   "title": "并发冲突、死锁",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{instance=\"$pg_exporter\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{instance=\"$pg_exporter\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "PostgreSQL DB 大小",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "最大连接数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{instance=\"$pg_exporter\"}"
    }
   ]
  },
  {
   "title": "工作内存",
   "type": "stat",
   "description": "Work Mem",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{instance=\"$pg_exporter\"}"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{instance=\"$pg_exporter\"}"
    }
   ]
  },
  {
   "title": "最大工作进程数",
   "type": "stat",
   "description": "Max Worker Processes",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{instance=\"$pg_exporter\"}"
    }
   ]
  },
  {
   "title": "最大并行工作进程数",
   "type": "stat",
   "description": "Max Parallel Workers",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{instance=\"$pg_exporter\"}"
    }
   ]
  },
  {
   "title": "维护工作内存",
   "type": "stat",
   "description": "Maintenance Work Mem",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{instance=\"$pg_exporter\"}"
    }
   ]
  },
  {
   "title": "有效缓存",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{instance=\"$pg_exporter\"}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "stat",
   "description": "Random Page Cost",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{instance=\"$pg_exporter\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{instance=\"$pg_exporter\"}"
    }
   ]
  },
  {
   "title": "锁表",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"$datname\", instance=~\"$pg_exporter\", mode=~\"$mode\"} != 0",
     "legendFormat": "{{datname}},{{mode}}"
    }
   ]
  },
  {
   "title": "数据库成功完成并提交的事务的数量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=\"$pg_exporter\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{instance=\"$pg_exporter\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "所有库已读取的行数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$pg_exporter\"})",
     "legendFormat": "所有库已读取的行数"
    }
   ]
  },
  {
   "title": "所有库已插入的行数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$pg_exporter\"})",
     "legendFormat": "所有库已插入的行数"
    }
   ]
  },
  {
   "title": "每个数据库读取到的行数的总数（SELECT）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$pg_exporter\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "插入数据（INSERT）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$pg_exporter\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "所有库已更新行数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$pg_exporter\"})",
     "legendFormat": "所有库已更新行数"
    }
   ]
  },
  {
   "title": "所有库返回行数总和",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"$pg_exporter\"})",
     "legendFormat": "所有库返回行数总和"
    }
   ]
  },
  {
   "title": "更新数据（UPDATE）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$pg_exporter\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "所有返回的行数总和",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"$pg_exporter\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "所有库已删除的总行数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$pg_exporter\"})",
     "legendFormat": "所有库已删除的总行数"
    }
   ]
  },
  {
   "title": "空闲sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$pg_exporter\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "删除数据（DELETE）",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"$pg_exporter\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "每个数据库在临时表、排序操作、哈希表等临时存储操作中使用的字节数",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{instance=\"$pg_exporter\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "等待的会话数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "pg_wait_session_sec{instance=\"$instance\"}",
     "legendFormat": "每秒处于等待的会话数"
    },
    {
     "expr": "pg_wait_session_five_sec{instance=\"$instance\"}",
     "legendFormat": "每5秒处于等待的会话数"
    }
   ]
  },
  {
   "title": "缓存命中率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{instance=\"$pg_exporter\", datname=~\"$datname\"} / (pg_stat_database_blks_read{instance=\"$pg_exporter\", datname=~\"$datname\"} + pg_stat_database_blks_hit{instance=\"$pg_exporter\", datname=~\"$datname\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "打开文件描述符",
   "type": "graph",
   "description": "打开文件描述符的数量",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$pg_exporter\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "当前活跃的连接数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$pg_exporter\", state=\"active\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  }
 ]
}